// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 19 Oct 2020 01:59:52 EEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "mpc_crypto.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

