// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 19 Oct 2020 01:59:52 EEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package mpc

/*
#include "mpc_crypto.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Mpc_step_flags_e as declared in include/mpc_crypto.h:93
type Mpc_step_flags_e int32

// Mpc_step_flags_e enumeration from include/mpc_crypto.h:93
const ()
